### ISSUE TITLE
Something that confused me

### ISSUE THREAD

**Issue by mdcallag** [tidesdb/tidesql#115]
I am building from source via the install.sh script using the notes you provide [here](https://github.com/tidesdb/tidesql#). The script is nice but I ended up doing the manual steps so I can set CMake options for MariaDB.

That page highlights the Tidesql version (v4.2.5 as I write this) but that isn't the version namespace I need to use for the --tidesdb-version argument. 

Once I figured that out I then tried to compile with MariaDB 12.3.1 which fails today. It would help if the web page was more clear on the versions that are supported. It states: _The pluggable engine is tested and supported on MariaDB 11.x, 12.x_ but 12.3.1 isn't working for me.

It builds OK with MariaDB 12.2.2

```
./install.sh --jobs 12 --tidesdb-version v9.0.9 --mariadb-version mariadb-12.3.1 --mariadb-prefix ~/d/ma120101_tides --allocator jemalloc --skip-engines columnstore,connect,federated,federatedx,mroonga,oqgraph,rocksdb,sphinx,spider

[ 48%] Building C object storage/maria/CMakeFiles/s3.dir/s3_func.c.o
[ 48%] Building C object plugin/auth_ed25519/CMakeFiles/auth_ed25519.dir/ref10/fe_sub.c.o
/tmp/tidesql-build/mariadb-server/storage/tidesdb/ha_tidesdb.cc: In member function ‘virtual int ha_tidesdb::open(const char*, int, uint)’:
/tmp/tidesql-build/mariadb-server/storage/tidesdb/ha_tidesdb.cc:49:40: error: ‘struct TABLE’ has no member named ‘option_struct’
   49 | #define TDB_TABLE_OPTIONS(tbl) ((tbl)->option_struct)
      |                                        ^~~~~~~~~~~~~
/tmp/tidesql-build/mariadb-server/storage/tidesdb/ha_tidesdb.cc:4399:13: note: in expansion of macro ‘TDB_TABLE_OPTIONS’
 4399 |         if (TDB_TABLE_OPTIONS(table))
      |             ^~~~~~~~~~~~~~~~~
/tmp/tidesql-build/mariadb-server/storage/tidesdb/ha_tidesdb.cc:49:40: error: ‘struct TABLE’ has no member named ‘option_struct’
   49 | #define TDB_TABLE_OPTIONS(tbl) ((tbl)->option_struct)
      |                                        ^~~~~~~~~~~~~
/tmp/tidesql-build/mariadb-server/storage/tidesdb/ha_tidesdb.cc:4401:28: note: in expansion of macro ‘TDB_TABLE_OPTIONS’
 4401 |             uint iso_idx = TDB_TABLE_OPTIONS(table)->isolation_level;
      |                            ^~~~~~~~~~~~~~~~~
/tmp/tidesql-build/mariadb-server/storage/tidesdb/ha_tidesdb.cc:49:40: error: ‘struct TABLE’ has no member named ‘option_struct’
   49 | #define TDB_TABLE_OPTIONS(tbl) ((tbl)->option_struct)
      |                                        ^~~~~~~~~~~~~
/tmp/tidesql-build/mariadb-server/storage/tidesdb/ha_tidesdb.cc:4407:13: note: in expansion of macro ‘TDB_TABLE_OPTIONS’
 4407 |         if (TDB_TABLE_OPTIONS(table)) share->default_ttl = TDB_TABLE_OPTIONS(table)->ttl;
      |             ^~~~~~~~~~~~~~~~~
/tmp/tidesql-build/mariadb-server/storage/tidesdb/ha_tidesdb.cc:49:40: error: ‘struct TABLE’ has no member named ‘option_struct’
   49 | #define TDB_TABLE_OPTIONS(tbl) ((tbl)->option_struct)
      |                                        ^~~~~~~~~~~~~
```

**Comment by guycipher** [comment]
Hi Mark, thank you for the issue.  I will work on the build errors, MariaDB likes to change critical engine pieces, moving includes, every patch, minor thus I have to conditionalize things quite often for different versions. 

At the end of the TideSQL reference I created a support table.

<img width="880" height="475" alt="Image" src="https://github.com/user-attachments/assets/963981e9-f57d-4520-bad1-b6340467eb94" />

https://tidesdb.com/reference/tidesql/#mariadb-compatibility:~:text=%E2%80%94-,MariaDB%20Compatibility,-MariaDB%20Version

Will update as MariaDB versions are tested, corrected and supported.

**Comment by guycipher** [comment]
"but that isn't the version namespace I need to use for the --tidesdb-version argument." yes this is true, when you install from repo its installing latest TideSQL.

**Comment by guycipher** [comment]
I've updated the read me, documentation to better guide on the version and flag semantics.  I've also merged my PR in which adds support for a condition that I had found I had to "as i had guessed" for 12.3.x, a patch yet a critical one.  Thank you Mark.
